services:
  scraper:
    build: scraper
    depends_on:
      - typesense
  typesense:
    image: typesense/typesense:0.21.0
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    ports:
      - "8108:8108"
    volumes:
      - "/tmp/typesense-data:/data"
  frontend:
    build: frontend
    depends_on:
      - typesense
    ports:
      - "4365:4365"
    volumes:
      - "./frontend:/app"
