import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Hits, InstantSearch, SearchBox } from "react-instantsearch-dom";
import TypesenseInstantSearchAdapter from "typesense-instantsearch-adapter";
import React from "react";
import Hit from "../components/Hit";
import CustomSearchBox from "../components/CustomSearchBox";

const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "xyz",
    nodes: [
      {
        host: "localhost",
        port: "8108",
        protocol: "http"
      }
    ]
  },
  additionalSearchParameters: {
    queryBy: "name,teachers,course_code,summary"
  }
});

const searchClient = typesenseInstantsearchAdapter.searchClient;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <InstantSearch indexName="courses" searchClient={searchClient}>
          <CustomSearchBox />
          <Hits hitComponent={Hit} />
        </InstantSearch>
      </main>
    </div>
  );
}
